name: CI

on:
  push: ~
  pull_request: ~
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 15.x]
        os: ['ubuntu-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build & lint & test
      run: npm run all
